title: "Sample Tech Radar"

collections:
  blips:
    output: true
  rings:
    sort_by: index
  quadrants:
    sort_by: index

defaults:
  - scope:
      path: ""
      type: "blips"
    values:
      layout: "blip"
  - scope:
      path: ""
    values:
      layout: "default"