title: "Sample Tech Radar"

collections:
  blips:
    output: true

defaults:
  - scope:
      path: ""
      type: "blips"
    values:
      layout: "blip"
      categories: []
      moved: 0
  - scope:
      path: ""
    values:
      layout: "default"